# Generated by Django 6.0 on 2025-12-14 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię domowe/rodowodowe')),
                ('gender', models.CharField(choices=[('M', 'Pies'), ('F', 'Suka')], default='M', max_length=2, verbose_name='Płeć')),
                ('birth_date', models.DateField(verbose_name='Data urodzenia')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('vaccinations', models.TextField(blank=True, null=True, verbose_name='Szczepienia')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Osiągnięcia')),
                ('weight', models.FloatField(help_text='Wpisz wagę w kilogramach', verbose_name='Waga (kg)')),
                ('height', models.FloatField(help_text='Wpisz wzrost w cm', verbose_name='Wzrost (cm)')),
                ('color', models.CharField(max_length=50, verbose_name='Umaszczenie')),
                ('status', models.CharField(choices=[('available', 'Dostępny'), ('reserved', 'Zarezerwowany'), ('sold', 'Sprzedany'), ('stayed', 'Został w hodowli')], default='available', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Pies',
                'verbose_name_plural': 'Psy',
            },
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa miotu (np. Litera A)')),
                ('birth_date', models.DateField(verbose_name='Data urodzenia')),
                ('father', models.ForeignKey(blank=True, limit_choices_to={'gender': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_litters', to='pets.dog', verbose_name='Ojciec')),
                ('mother', models.ForeignKey(blank=True, limit_choices_to={'gender': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_litters', to='pets.dog', verbose_name='Matka')),
            ],
            options={
                'verbose_name': 'Miot',
                'verbose_name_plural': 'Mioty',
            },
        ),
        migrations.AddField(
            model_name='dog',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dogs', to='pets.litter', verbose_name='Miot'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dog_photos/', verbose_name='Zdjęcie')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pets.dog')),
                ('litter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pets.litter')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blog.post')),
            ],
            options={
                'verbose_name': 'Zdjęcie',
                'verbose_name_plural': 'Zdjęcia',
            },
        ),
    ]
