# Generated by Django 6.0 on 2025-12-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='dog_avatar/', verbose_name='Główne zdjęcie'),
        ),
        migrations.AddField(
            model_name='litter',
            name='boys_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Liczba samców'),
        ),
        migrations.AddField(
            model_name='litter',
            name='girls_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Liczba samic'),
        ),
        migrations.AddField(
            model_name='photo',
            name='avatar',
            field=models.BooleanField(default=False, verbose_name='Czy zdjęcie profilowe?'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('M', 'Samiec'), ('F', 'Samica')], default='M', max_length=2, verbose_name='Płeć'),
        ),
    ]
