# Generated by Django 6.0 on 2025-12-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_dog_main_image_litter_boys_count_litter_girls_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='avatar',
        ),
    ]
